TARGET = driver

BNO_SENSOR_DIRECTORY = BNO055_OPI_5_PLUS
MOVING_PARTS_DIRECTORY = moving_parts
SENSORS_DIRECTORY = sensors

CC = g++
CFLAGS = -Wall -g 
POST_CFLAGS = -l wiringPi

all: $(TARGET)
 
$(TARGET): $(TARGET).o $(BNO_SENSOR_DIRECTORY)/Adafruit_I2CDevice.o $(BNO_SENSOR_DIRECTORY)/Adafruit_Sensor.o $(BNO_SENSOR_DIRECTORY)/Adafruit_BNO055.o $(MOVING_PARTS_DIRECTORY)/motor.o $(SENSORS_DIRECTORY)/extra_i2c.o $(SENSORS_DIRECTORY)/ina219.o 
			$(CC) $(CFLAGS) -o $(TARGET) $(TARGET).o $(BNO_SENSOR_DIRECTORY)/Adafruit_I2CDevice.o $(BNO_SENSOR_DIRECTORY)/Adafruit_Sensor.o $(BNO_SENSOR_DIRECTORY)/Adafruit_BNO055.o $(MOVING_PARTS_DIRECTORY)/motor.o $(SENSORS_DIRECTORY)/extra_i2c.o $(SENSORS_DIRECTORY)/ina219.o  $(POST_CFLAGS)

$(TARGET).o: $(TARGET).cpp $(BNO_SENSOR_DIRECTORY)/Adafruit_I2CDevice.h $(BNO_SENSOR_DIRECTORY)/Adafruit_Sensor.h $(BNO_SENSOR_DIRECTORY)/Adafruit_BNO055.h $(MOVING_PARTS_DIRECTORY)/motor.h $(SENSORS_DIRECTORY)/ina219.h $(SENSORS_DIRECTORY)/extra_i2c.h
			$(CC) $(CFLAGS) -c $(TARGET).cpp 

clean:
			$(RM) $(TARGET) $(TARGET).o $(BNO_SENSOR_DIRECTORY)/Adafruit_I2CDevice.o $(BNO_SENSOR_DIRECTORY)/Adafruit_Sensor.o $(BNO_SENSOR_DIRECTORY)/Adafruit_BNO055.o $(MOVING_PARTS_DIRECTORY)/motor.o $(SENSORS_DIRECTORY)/ina219.o $(SENSORS_DIRECTORY)/extra_i2c.o



$(BNO_SENSOR_DIRECTORY)/Adafruit_BNO055.o: $(BNO_SENSOR_DIRECTORY)/Adafruit_BNO055.h $(BNO_SENSOR_DIRECTORY)/Adafruit_I2CDevice.h $(BNO_SENSOR_DIRECTORY)/Adafruit_Sensor.h $(BNO_SENSOR_DIRECTORY)/utility/imumaths.h $(BNO_SENSOR_DIRECTORY)/utility/matrix.h $(BNO_SENSOR_DIRECTORY)/utility/quaternion.h $(BNO_SENSOR_DIRECTORY)/utility/vector.h

$(BNO_SENSOR_DIRECTORY)/Adafruit_I2CDevice.o: $(BNO_SENSOR_DIRECTORY)/Adafruit_I2CDevice.h

$(BNO_SENSOR_DIRECTORY)/Adafruit_Sensor.o: $(BNO_SENSOR_DIRECTORY)/Adafruit_Sensor.h 

$(MOVING_PARTS_DIRECTORY)/motor.o: $(MOVING_PARTS_DIRECTORY)/motor.h

$(SENSORS_DIRECTORY)/ina219.o: $(SENSORS_DIRECTORY)/ina219.h $(SENSORS_DIRECTORY)/extra_i2c.h

$(SENSORS_DIRECTORY)/extra_i2c.o: $(SENSORS_DIRECTORY)/extra_i2c.h


# run: $(shell sudo ./$(TARGET))